name: Public Npm

on:
  push:
    branches: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Build
        run: cd packages/pup-ui && pnpm run build
      - name: NPM Publish
        uses: wistia/publish-branch-to-npm@v1.0.0
        with:
          # GitHub authorization token
          github_token: ${{ secrets.TOKEN }}
          # npm authorization token
          npm_token: ${{ secrets.NPM_AUTH_TOKEN }}
          # if true, will run without actually publishing to npm
          dry_run: false
